trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore 
  displayName: restoring project
- script: dotnet build src/AzInsurance.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '# Write your powershell commands here.
    Write-Host "Hello World"