# ASP.NET Core
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '# Write your powershell commands here.
      
      Write-Host "Hello World"
      Write-Host "Hello World2"
      # Use the environment variables input below to pass secret variables to this script.'
    errorActionPreference: 'continue'
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore 
  displayName: restoring project
- script: dotnet build src/AzInsurance.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

